# 스프링 어플리케이션명 설정
spring.application.name=study-springboot

# 스프링 어플리케이션 타입 설정
# spring.main.web-application-type=none

# 수동 포트 설정(HTTPS가 설정된 포트로 변경)
server.port=8443 

# 랜덤 포트 설정
# server.port=0

# 콘솔창 색상
spring.output.ansi.enabled=always

# HTTPS 설정
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=123456
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=tomcat

# HTTP2 설정(SSL설정 선행적용 필수, tomcat8.5이하 버전 && jdk9이하 버전에서는 추가 설정이 필요함, 현재는 톰캣10에 jdk21이라 해당 설정만 필요함)
server.http2.enabled=true