spring.application.name=study-springboot
# ???? ??????? ??? ???? ?? ??
# spring.main.web-application-type=none
# ?? ?? ??
# server.port=7070
# ?? ?? ??
server.port=0
# ??? ?? ??? ??
spring.output.ansi.enabled=always